### ISSUE TITLE
Error on start node with v0.1.16

### ISSUE THREAD

**Issue by zaketac** [Phala-Network/khala-parachain#138]
docker logs 322428f9acb9 -f --tail 10
  24: clone

Thread 'tokio-runtime-worker' panicked at 'SinkImpl::poll_flush called after error.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/quicksink-0.1.2/src/lib.rs:225

This is a bug. Please report it at:

        https://github.com/Phala-Network/khala-parachain/issues/new

./start_node.sh: line 70:     8 Segmentation fault      (core dumped) /usr/local/bin/khala-node --chain $PARACHAIN --base-path $DATA_PATH --name $NODE_NAME --port $PARACHAIN_PORT --prometheus-port 9615 --rpc-port 9933 --ws-port 9944 --prometheus-external --ws-external --rpc-cors all --no-hardware-benchmarks $PARACHAIN_ROLE_ARGS $PARACHAIN_EXTRA_ARGS -- --chain $RELAYCHAIN --port $RELAYCHAIN_PORT --prometheus-port 9616 --rpc-port 9934 --ws-port 9945 --prometheus-external --ws-external --rpc-cors all --no-hardware-benchmarks $RELAYCHAIN_ROLE_ARGS $RELAYCHAIN_EXTRA_ARGS

**Comment by jasl** [comment]
Upstream issue <https://github.com/libp2p/rust-libp2p/issues/2598>

**Comment by zaniko** [comment]
Hey @jasl restarted the node and even the machine a few times but still getting it. What do you mean by restart, maybe I'm missing something?

**Comment by jasl** [comment]
> Hey @jasl restarted the node and even the machine a few times but still getting it. What do you mean by restart, maybe I'm missing something?

when you use khala-node docker image, you can add `--restart=always` so if the problem occurred, it will restart automatically, and clients (pherry, prb and polkadot.js) will auto reconnect

**Comment by zaniko** [comment]
> > Hey @jasl restarted the node and even the machine a few times but still getting it. What do you mean by restart, maybe I'm missing something?
> 
> when you use khala-node docker image, you can add `--restart=always` so if the problem occurred, it will restart automatically, and clients (pherry, prb and polkadot.js) will auto reconnect
> 
> more doc about Docker auto-restart you can check https://docs.docker.com/config/containers/start-containers-automatically/

ok many thanks, checking it

**Comment by jasl** [comment]
latest khala-node fixed this
phalanetwork/khala-node:v0.1.17
DIGEST:sha256:d69bbc8cdecf152a891f5c1b32028da680b51ca716443207136ffc824a191ff7
WARNING: once upgrade, you can't downgrade to previous version
