### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zaniko** [Phala-Network/khala-parachain#139]
Version: 0.1.16-dev-3b68cd70487

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/panicking.rs:143:14
   6: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::get
   7: <sc_client_db::StorageDb<Block> as sp_state_machine::trie_backend_essence::Storage<<<Block as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Hashing>>::get
   8: <sp_state_machine::trie_backend_essence::TrieBackendEssence<S,H> as hash_db::HashDB<H,alloc::vec::Vec<u8>>>::get
   9: <sp_state_machine::trie_backend_essence::TrieBackendEssence<S,H> as hash_db::HashDBRef<H,alloc::vec::Vec<u8>>>::get
  10: trie_db::Trie::get
  11: sp_state_machine::trie_backend_essence::TrieBackendEssence<S,H>::storage
  12: <sc_client_db::storage_cache::CachingState<S,B> as sp_state_machine::backend::Backend<<<B as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Hashing>>::storage
  13: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
  14: sp_io::storage::get_version_1
  15: sp_io::storage::ExtStorageGetVersion1::call
  16: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: wasmtime_runtime::traphandlers::catch_traps::call_closure
  29: wasmtime_setjmp
  30: sc_executor_wasmtime::runtime::perform_call
  31: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call
  32: sc_executor_common::wasm_runtime::WasmInstance::call_export
  33: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  34: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  35: <polkadot_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  37: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  40: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  41: sc_consensus::import_queue::basic_queue::block_import_process::{{closure}}
  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  43: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  44: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  45: tokio::runtime::task::raw::poll
  46: std::sys_common::backtrace::__rust_begin_short_backtrace
  47: core::ops::function::FnOnce::call_once{{vtable.shim}}
  48: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/sys/unix/thread.rs:108:17
  49: start_thread
  50: clone

Thread 'tokio-runtime-worker' panicked at 'Critical database error: Custom { kind: Other, error: Error { message: "IO error: While pread offset 12611434 len 8673: /root/data/polkadot/chains/ksmcc3/db/full/193983.sst: Input/output error" } }', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/257cdb5/primitives/database/src/kvdb.rs:29

**Comment by jasl** [comment]
Sorry, this is an upstream bug, see https://github.com/libp2p/rust-libp2p/issues/2598

**Comment by zaniko** [comment]
Hey, thank you. Reading through it right now. It might look dumb but what does it mean in few words?

**Comment by jasl** [comment]
> Hey, thank you. Reading through it right now. It might look dumb but what does it mean in few words?

we have to wait upstream fix, for now, it occurred randomly, but if you set auto-restart for khala docker container, it should be OK, Pherry and PRB can auto-reconnect to the node

**Comment by jasl** [comment]
Hi can you show me your memory usage when running khala-node?

**Comment by jasl** [comment]
latest khala-node fixed this
phalanetwork/khala-node:v0.1.17
DIGEST:sha256:d69bbc8cdecf152a891f5c1b32028da680b51ca716443207136ffc824a191ff7
WARNING: once upgrade, you can't downgrade to previous version
