### ISSUE TITLE
Crash part2

### ISSUE THREAD

**Issue by zaniko** [Phala-Network/khala-parachain#140]
Version: 0.1.16-dev-3b68cd70487

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/panicking.rs:143:14
   6: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::get
   7: <sc_client_db::StorageDb<Block> as sp_state_machine::trie_backend_essence::Storage<<<Block as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Hashing>>::get
   8: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::have_state_at
   9: sc_client_db::Backend<Block>::try_commit_operation
  10: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
  11: cumulus_client_consensus_common::parachain_consensus::run_parachain_consensus::{{closure}}::{{closure}}::{{closure}}
  12: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  13: tokio::runtime::task::harness::poll_future
  14: tokio::runtime::task::raw::poll
  15: tokio::runtime::thread_pool::worker::Context::run_task
  16: tokio::runtime::thread_pool::worker::run
  17: tokio::runtime::task::raw::poll
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/sys/unix/thread.rs:108:17
  21: start_thread
  22: clone

Thread 'tokio-runtime-worker' panicked at 'Critical database error: Custom { kind: Other, error: Error { message: "IO error: While pread offset 38788880 len 13883: /root/data/chains/khala/db/full/033868.sst: Input/output error" } }', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/257cdb5/primitives/database/src/kvdb.rs:29

**Comment by jasl** [comment]
Let's discuss in #139
