### ISSUE TITLE
Error on start node

### ISSUE THREAD

**Issue by Aun-JY** [Phala-Network/khala-parachain#153]
### 
I tried node restart and set --restart=always

When I restart a node, the error repeats..

pherry syne is not decreasing but increasing

====================

Version: 0.1.16-82d9a956a2b

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/panicking.rs:143:14
   6: core::result::unwrap_failed
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/core/src/result.rs:1785:5
   7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
   8: sp_io::storage::get_version_1
   9: sp_io::storage::ExtStorageGetVersion1::call
  10: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: wasmtime_runtime::traphandlers::catch_traps::call_closure
  23: wasmtime_setjmp
  24: sc_executor_wasmtime::runtime::perform_call
  25: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call
  26: sc_executor_common::wasm_runtime::WasmInstance::call_export
  27: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  28: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  29: <khala_parachain_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
  30: sp_api::Core::execute_block
  31: rayon::iter::plumbing::bridge_producer_consumer::helper
  32: <phala_node_rpc_ext::NodeRpcExt<BE,Block,Client,P> as phala_node_rpc_ext::NodeRpcExtApiServer<<Block as sp_runtime::traits::Block>::Hash>>::get_storage_changes
  33: jsonrpsee_core::server::rpc_module::RpcModule<Context>::register_method::{{closure}}
  34: jsonrpsee_ws_server::server::background_task::{{closure}}
  35: tokio::runtime::task::harness::poll_future
  36: tokio::runtime::task::raw::poll
  37: tokio::runtime::thread_pool::worker::Context::run_task
  38: tokio::runtime::thread_pool::worker::run
  39: tokio::runtime::task::raw::poll
  40: std::sys_common::backtrace::__rust_begin_short_backtrace
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/0677edc86e342f333d4828b0ee1ef395a4e70fe5/library/std/src/sys/unix/thread.rs:108:17
  43: start_thread
  44: clone

Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x5e5f9c2927451056342eaa077c19af27cafc93e3162098e7c4bf8f3ea9bd25c9"', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/814752f/primitives/state-machine/src/ext.rs:189

This is a bug. Please report it at:

        https://github.com/Phala-Network/khala-parachain/issues/new

![image](https://user-images.githubusercontent.com/109011870/180577267-36fca4d9-cbb9-4c1d-9ba8-a01c1e4de69d.png)

**Comment by jasl** [comment]
dupplicate with https://github.com/Phala-Network/khala-parachain/issues/138

have to restart for now

**Comment by jasl** [comment]
Hi can you show me your memory usage when running khala-node?

**Comment by Aun-JY** [comment]
![image](https://user-images.githubusercontent.com/109011870/181203946-94d9fae5-be60-4622-99c1-04b329960a45.png)

**Comment by Aun-JY** [comment]
Node stopped after restart.
So I am synchronizing after Re-installing OS.
