### ISSUE TITLE
Insufficient peers for Phala Parachain syncing -- need correct bootnodes?

### ISSUE THREAD

**Issue by sourabhniyogi** [Phala-Network/khala-parachain#155]
Our phala node isn't syncing to the tip and is stuck on block 90051 for 18+ hours:
```
2022-07-31 16:44:23 [Relaychain] 💤 Idle (50 peers), best: #11404419 (0xb0af…67fd), finalized #11404415 (0x709b…8792), ⬇ 158.3kiB/s ⬆ 155.6kiB/s    
2022-07-31 16:44:23 [Parachain] 💤 Idle (1 peers), best: #90051 (0x5d96…2488), finalized #90051 (0x5d96…2488), ⬇ 1.0kiB/s ⬆ 1.3kiB/s    
```
Repeated restarts are not helping.  The blockhashes are correct on both relaychain + parachain so I believe the spec is correct.

Our invocation, which we believe to be correct, is: 
```
./target/release/khala-node --name phala --base-path /root/.local/share/phala/ --chain /khala/khala-parachain/node/res/phala.json --state-cache-size 1 --db-cache 2048 --runtime-cache-size 32 --rpc-methods Unsafe --unsafe-rpc-external --rpc-port 9100 --rpc-external --ws-external --ws-port 9944 --unsafe-ws-external --rpc-max-payload 64 --collator --pruning archive --no-prometheus --rpc-cors all 
```
Our goal is to run full node to support trace / XCM transfer indexing in https://phala.polkaholic.io -- 

Are the correct bootnodes specified here in the chain spec and used?
```
# head  /khala/khala-parachain/node/res/phala.json
{
  "name": "Phala",
  "id": "phala",
  "chainType": "Live",
  "bootNodes": [
    "/dns4/phala-node-hk.phala.network/tcp/30333/ws/p2p/12D3KooWAPkEheyc7QcP3Mhf4iJdmCaPN9aHUofyKTE1an4g2PCK",
    "/dns4/phala-node-eu.phala.network/tcp/30333/ws/p2p/12D3KooWGSQvEFii28GeN1EKG7vWj6VEfM3Md8Z25nEpbzR6k3yc",
    "/dns4/phala-node-us.phala.network/tcp/30333/ws/p2p/12D3KooWKzDSCdMpLEKCR9nEfS7arW7mmH2VyVur4XM4GgaffjeY"
  ],
```

Please advise -- Thank you!

**Comment by jasl** [comment]
If you wanna compile by yourself, you have to use https://github.com/Phala-Network/khala-parachain/tree/phala-runtime-1151 for Phala for now

or you may use https://hub.docker.com/repository/registry-1.docker.io/phalanetwork/phala-node/tags?page=1&ordering=last_updated

The reason is Cumulus client doesn't support codeSubstitutes for now, we used that tech to fix trouble

**Comment by jasl** [comment]
Correct: should use https://github.com/Phala-Network/khala-parachain/tree/rescue

**Comment by sourabhniyogi** [comment]
Thank you -- will attempt in the next 24 hrs
