### ISSUE TITLE
Integrate Sygma pallets into SubBridge

### ISSUE THREAD

**Issue by tolak** [Phala-Network/khala-parachain#250]
# Integrate Sygma pallets into SubBridge

This issue describes the technical details of how we integrate [Sygma pallets](https://github.com/sygmaprotocol/sygma-substrate-pallets) into SubBridge.

SubBridge core module [xtransfer](https://github.com/Phala-Network/khala-parachain/blob/main/pallets/subbridge/src/xtransfer.rs) support assembles any bridge that implements trait [BridgeTransact](https://github.com/Phala-Network/khala-parachain/blob/8dd74af5d5930fef4bdada4be676919071da2c90/pallets/subbridge/src/traits.rs#L41). The bridge can be configured as a bridge instance of SubBridge routing protocol, [here](https://github.com/Phala-Network/khala-parachain/blob/8dd74af5d5930fef4bdada4be676919071da2c90/runtime/khala/src/lib.rs#L1523) is the configuration in Khala network. SubBridge can forward messages between those bridges.

## Sygma Wrapper

Sygma bridge pallet only provides the primitives and extrinsic to transfer assets between Substrate chains and EVM chains, to make the Sygma protocol adapts SubBridge routing protocol, we need to introduce a wrapper pallet that mainly implements the trait `BridgeTransact`. A draft implementation can be found [here](https://github.com/Phala-Network/khala-parachain/blob/sygma-integration/pallets/subbridge/src/sygma_wrapper.rs).

The simple logic of transferring assets to EVM chains can be described as:

`xtransfer.transfer() -> sygma_wrapper.transfer_fungible() -> sygma_bridge.deposit()`

The draft code can be found [here](https://github.com/Phala-Network/khala-parachain/blob/8c71f033e73ff1a870761fbdf8c34117384e53f8/pallets/subbridge/src/sygma_wrapper.rs#L83)

The simple logic of transferring assets from EVM chains to other parachains (including local Substrate chains) can be described as:

`sygma_bridge.relayers -> sygma_bridge.execute_proposal() -> sygma_bridge.AssetTransactor.deposit_asset() -> XTransferAdapter.deposit_asset() -> other bridges`

Note that we configured [XTransferAdapter](https://github.com/Phala-Network/khala-parachain/blob/8dd74af5d5930fef4bdada4be676919071da2c90/pallets/subbridge/src/fungible_adapter.rs#L9) as the `AssetTransactor` of Sygma bridge, it makes SubBridge routing protocol take over the asset transactor. See draft code [here](https://github.com/Phala-Network/khala-parachain/blob/8c71f033e73ff1a870761fbdf8c34117384e53f8/runtime/thala/src/lib.rs#L1596).

Besides, the Sygma wrapper also implements traits `ExtractRecipient` and `ExtractDomainID`, so the dest location identification will depend on the format that SubBridge used.

Sygma Wrapper does not contains any extrinsic, we don't need to config any authority strategy.

## Sygma Bridge Config

A draft config can be found [here](https://github.com/Phala-Network/khala-parachain/blob/8c71f033e73ff1a870761fbdf8c34117384e53f8/runtime/thala/src/lib.rs#L1588). Compared with simple example config in Sygma repo, following items should be highlighted:

- AssetTransactor

As we mentioned above, we use SubBridge `XTransferAdapter` will be configured as asset transactor implementation.

- ResourcePairs

We configured `ResourcePairs` with `AssetsRegistry`, the latter implements `Get<Vec<(XcmAssetId, ResourceId)>>` which returns the resource id pair information for all registered assets in Khala network. In other words, it is dynamic instead of hard code in runtime. See draft code [here](https://github.com/Phala-Network/khala-parachain/blob/8c71f033e73ff1a870761fbdf8c34117384e53f8/pallets/assets-registry/src/lib.rs#L828).

## Authority management

Like the example configuration in the Sygma repo, the `BridgeCommitteeOrigin` of `sygma_access_segregator`, `sygma_basic_feehandler`, `sygma_fee_handler_router` and `sygma_bridge` are configured as `EnsureRootOrHalfCouncil`. On the production network (Khala and Phala), there is no root exists, on-chain governance (council) will be the role that management bridges.

We still can use `sygma_access_segregator` to apply different permission to a specific account.

## Bridge fee

Bridge still can be set through `sygma_basic_feehandler` and be routed by `sygma_fee_handler_router`. SubBridge routing protocol doesn't impact fee logic.

**Comment by freddyli7** [comment]
@tolak few questions here:
1. You mentioned `Sygma Wrapper does contains any extrinsic, we don't need to config any authority strategy.` you mean does or does not?
2. `authority strategy` here in this sygma wrapper should depend on the authority strategy that defined in each pallet in `sygma-pallets` repo, like the `access-segregator` access control logic, correct? the only difference is that there will be no `root`, instead there will be on-chain gov, in such case, in the init stage of launching, on-chain gov shall be able to call `grant_access` extrinsic to grant other access to other accounts, correct?
