### ISSUE TITLE
Fix bounty configuration

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/khala-parachain#265]
When proposing a bounty, there's a config `type SpendOrigin` in treasury config to approve the bounty. So far the config at Khala & Phala is `frame_support::traits::NeverEnsureOrigin<u128>`, which means nobody can approve the bounty.

Suggested to change it to:

```
    type SpendOrigin = frame_system::EnsureWithSuccess<
        frame_support::traits::EitherOf<
            EnsureRoot<AccountId>,
            pallet_collective::EnsureProportionMoreThan<AccountId, CouncilCollective, 1, 2>,
        >,
        AccountId, MaxBalance,
    >;
```

**Comment by jasl** [comment]
Addressed by https://github.com/Phala-Network/khala-parachain/pull/263/commits/d85ac8e00409f7b4ec3a4fbd5b21e5569f766191
