### ISSUE TITLE
Primitive cast to u8 although underlying u128

### ISSUE THREAD

**Issue by Chralt98** [Phala-Network/khala-parachain#296]
Hey Phala team,

I found this 

https://github.com/Phala-Network/khala-parachain/blob/83ee61543240d2da5e9a21882fc65658fed7c1cd/pallets/subbridge/src/sygma_wrapper.rs#L65

The `GeneralIndex` is `u128` from [here](https://github.com/paritytech/polkadot/blob/70d80aa7441de1494bd422024236d59fd25e7252/xcm/src/v3/junction.rs#L297). How do you ensure the cast is valid? I mean `u128 as u8` uses modulo, but it has collisions.

**Comment by tolak** [comment]
@Chralt98 Thanks for submitting this issue, we will fix it as soon as possible.
