### ISSUE TITLE
Add Acala kUSD to Khala

### ISSUE THREAD

**Issue by tolak** [Phala-Network/khala-parachain#73]

**Comment by gluneau** [comment]
kUSD:
```
{
  "parents": 1,
  "interior": {
    "X2": [
      {
        "Parachain": 2000
      },
      {
        "GeneralKey": [
          0,
          129
        ]
      }
    ]
  }
}
```

**Comment by tolak** [comment]
@gluneau Waitting to be merged, see [this PR](https://github.com/Phala-Network/khala-parachain/pull/74)

**Comment by tolak** [comment]
@gluneau PR merged, kUSD transfer will be enabled after next runtime upgrade. Let me close this issue.

**Comment by gluneau** [comment]
Has there been a runtime upgrade?  When is the next one scheduled?

**Comment by gluneau** [comment]
@tolak  When is the next one scheduled? Or has there been a runtime upgrade?

**Comment by tolak** [comment]
@gluneau Hi, sorry i forgot to inform you, kUSD already transferable between Karura and Khala, we did runtime upgrade last week
